### ISSUE TITLE
Petition to rename from `discord.why` -> `discord.whywouldyouwritethis`

### ISSUE THREAD

**Issue by 215B5D** [rpie/discord.why#1]
I'm unsure as to what gave you the motivation for this, however, there are major issues.
This project is clearly used for interacting with user accounts, not bot accounts.

Here are a few issues with the code:
- It's messy in general, way better ways to do things
- You're using different API versions for different functions
  - `v9`
     - `send_message()`, `delete_message()`, `create_reaction()`
  - `v7`
     - `check_nitro_status()`, `check_verified()`
  - `v6`
     - `check_token()`, `buy_nitro()`
- Invalid headers
   - You're not sending the correct headers for different endpoints, Discord sometimes expects a fingerprint & other data to be provided, this could lead to your account being terminated for API abuse

If you're going to publish something like this, at least do your research on the Discord API instead of blatantly taking endpoints from other projects & throwing them into some tiny wrapper

**Comment by Soliux** [comment]
I could not have said it any better myself. This project was written by a overdeveloped monkey.

**Comment by rpie** [comment]
## Project Usage

I did not state it in the [README.md](https://github.com/rpie/discord.why/#readme), but yes this project is for interacting with user accounts, and not bot accounts 

_____________________________

## Version Issues

As stated in the Discord update logs as of As of October 27th, 2020 the events under the GUILD_PRESENCES and GUILD_MEMBERS intents will be turned off by default on all gateway versions.

Due to the things I am writing doesn't support bot accounts and would not be able to grab account information without being phone locked in v7/9; v6 is deprecated but still supports these actions

Source talking about [v6 restrictions](https://discord.com/developers/docs/change-log#gateway-v6-intent-restrictions)

## Fingerprinting and Header Data

I haven't read *all* of the documentation for Discord, but I am pretty sure that fingerprint data is only required for gateway events and updates. I will look more into this and thank you for pointing it out, reading into the [Discord gateway payload docs](https://discord.com/developers/docs/topics/gateway#payloads) I can see that fingerprinting is needed to out-site abuse for their gateway events.
<html><body>
<h6 class="h6-3ZuB-g" id="payloads-gateway-payload-structure">Gateway Payload Structure<a tabindex="0" class="anchor-3Z-8Bb hyperlink" href="https://discord.com/developers/docs/topics/gateway#payloads-gateway-payload-structure" role="button"><div name="payloads-gateway-payload-structure"></div></a></h6>

Field | Type | Description
-- | -- | --
op | integer | opcode for the payload
d | ?mixed (any JSON value) | event data
s | ?integer * | sequence number, used for resuming sessions and heartbeats
t | ?string * | the event name for this payload


</body>
</html>

## Updates and talk

Thank you for pointing out my mistakes; if you'd like to correct them you can make a [pull-request here](https://github.com/rpie/discord.why/compare) or wait for further updates on the project, after all this is just for me and my fun :)

_____________________________

-> HellSec

**Comment by 215B5D** [comment]
Just remember, the Discord documentation won't provide insight for their private API, especially not the things they've put in place to remove spam / raid bots from the platform.

Experiment yourself, get an active web socket connection to their gateway (this is semi-documented) & check out the headers they send. 

Furthermore, the fingerprint is implemented through `X-Fingerprint` and can be fetched from `/experiments` iirc

**Comment by rpie** [comment]
I'll check this out more and experiment thank you for telling me :)

**Comment by Soliux** [comment]
@rpie Here take a look at some leet code for interacting with discord api that does not get the tokens banned: https://github.com/Sympthey/DiscSpam
